package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

// dockerOptions controls Dockerfile + compose.yaml generation.
type dockerOptions struct {
	db       string // sqlite | postgres | pgvector | mysql
	port     int
	binary   string // path to the built binary the Dockerfile COPYs
	force    bool
}

var validDBs = map[string]bool{"sqlite": true, "postgres": true, "pgvector": true, "mysql": true}

// runDocker generates the Dockerfile + compose.yaml without (re)building.
func runDocker(args []string) int {
	if hasHelpFlag(args) {
		printDockerHelp(os.Stdout)
		return 0
	}
	opts := dockerOptions{db: "sqlite", port: 8080, binary: "build/app"}
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--db":
			if i+1 < len(args) {
				i++
				opts.db = args[i]
			}
		case "--port":
			if i+1 < len(args) {
				i++
				p, err := strconv.Atoi(args[i])
				if err != nil {
					fmt.Fprintf(os.Stderr, "gebweb docker: invalid --port %q\n", args[i])
					return 2
				}
				opts.port = p
			}
		case "--out":
			if i+1 < len(args) {
				i++
				opts.binary = args[i]
			}
		case "--force":
			opts.force = true
		}
	}
	if err := generateDocker(opts); err != nil {
		fmt.Fprintf(os.Stderr, "gebweb docker: %v\n", err)
		return 1
	}
	return 0
}

// generateDocker writes Dockerfile and compose.yaml for the chosen DB. Existing
// files are left untouched unless opts.force is set.
func generateDocker(opts dockerOptions) error {
	if !validDBs[opts.db] {
		return fmt.Errorf("unknown --db %q (want sqlite, postgres, pgvector, or mysql)", opts.db)
	}
	if err := writeGenerated("Dockerfile", dockerfileContent(opts), opts.force); err != nil {
		return err
	}
	if err := writeGenerated("compose.yaml", composeContent(opts), opts.force); err != nil {
		return err
	}
	return nil
}

func writeGenerated(path, content string, force bool) error {
	if !force && fileExists(path) {
		fmt.Printf("gebweb docker: %s exists; left unchanged (use --force to overwrite)\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

func dockerfileContent(opts dockerOptions) string {
	port := strconv.Itoa(opts.port)
	notices := opts.binary + ".NOTICES.txt"
	return "# Generated by `gebweb docker`. Re-run with --force to regenerate.\n" +
		"# The app binary is built on the host by `gebweb build`; this image\n" +
		"# copies the static, CGO-free binary into a minimal distroless base.\n" +
		"FROM gcr.io/distroless/static-debian12\n" +
		"COPY " + opts.binary + " /app\n" +
		"COPY " + notices + " /app.NOTICES.txt\n" +
		"ENV GEBWEB_PORT=" + port + "\n" +
		"EXPOSE " + port + "\n" +
		"ENTRYPOINT [\"/app\"]\n"
}

func composeContent(opts dockerOptions) string {
	port := strconv.Itoa(opts.port)
	var sb strings.Builder
	b := &sb
	fmt.Fprintln(b, "# Generated by `gebweb docker`. Re-run with --force to regenerate.")
	fmt.Fprintln(b, "services:")
	fmt.Fprintln(b, "  app:")
	fmt.Fprintln(b, "    build: .")
	fmt.Fprintln(b, "    ports:")
	fmt.Fprintf(b, "      - \"${GEBWEB_PORT:-%s}:${GEBWEB_PORT:-%s}\"\n", port, port)
	fmt.Fprintln(b, "    env_file:")
	fmt.Fprintln(b, "      - .env")

	hasDB := opts.db == "postgres" || opts.db == "pgvector" || opts.db == "mysql"
	if hasDB {
		fmt.Fprintln(b, "    depends_on:")
		fmt.Fprintln(b, "      db:")
		fmt.Fprintln(b, "        condition: service_healthy")
	} else {
		// sqlite: persist the database file in a named volume.
		fmt.Fprintln(b, "    volumes:")
		fmt.Fprintln(b, "      - appdata:/data")
	}

	switch opts.db {
	case "postgres", "pgvector":
		image := "postgres:16"
		if opts.db == "pgvector" {
			image = "pgvector/pgvector:pg16"
		}
		fmt.Fprintln(b, "  db:")
		fmt.Fprintf(b, "    image: %s\n", image)
		fmt.Fprintln(b, "    environment:")
		fmt.Fprintln(b, "      POSTGRES_USER: ${POSTGRES_USER:-app}")
		fmt.Fprintln(b, "      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}")
		fmt.Fprintln(b, "      POSTGRES_DB: ${POSTGRES_DB:-app}")
		fmt.Fprintln(b, "    volumes:")
		fmt.Fprintln(b, "      - dbdata:/var/lib/postgresql/data")
		fmt.Fprintln(b, "    healthcheck:")
		fmt.Fprintln(b, "      test: [\"CMD-SHELL\", \"pg_isready -U ${POSTGRES_USER:-app}\"]")
		fmt.Fprintln(b, "      interval: 5s")
		fmt.Fprintln(b, "      timeout: 5s")
		fmt.Fprintln(b, "      retries: 10")
	case "mysql":
		fmt.Fprintln(b, "  db:")
		fmt.Fprintln(b, "    image: mysql:8")
		fmt.Fprintln(b, "    environment:")
		fmt.Fprintln(b, "      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}")
		fmt.Fprintln(b, "      MYSQL_USER: ${MYSQL_USER:-app}")
		fmt.Fprintln(b, "      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}")
		fmt.Fprintln(b, "      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}")
		fmt.Fprintln(b, "    volumes:")
		fmt.Fprintln(b, "      - dbdata:/var/lib/mysql")
		fmt.Fprintln(b, "    healthcheck:")
		fmt.Fprintln(b, "      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]")
		fmt.Fprintln(b, "      interval: 5s")
		fmt.Fprintln(b, "      timeout: 5s")
		fmt.Fprintln(b, "      retries: 10")
	}

	fmt.Fprintln(b, "volumes:")
	if hasDB {
		fmt.Fprintln(b, "  dbdata:")
	} else {
		fmt.Fprintln(b, "  appdata:")
	}
	return sb.String()
}

func printDockerHelp(w io.Writer) {
	fmt.Fprintln(w, "usage: gebweb docker [--db <driver>] [--port <port>] [--out <path>] [--force]")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Generate a Dockerfile and compose.yaml for the project. The")
	fmt.Fprintln(w, "Dockerfile copies the host-built binary (from `gebweb build`)")
	fmt.Fprintln(w, "into a distroless image; compose.yaml wires GEBWEB_PORT, .env,")
	fmt.Fprintln(w, "and an optional database service.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Existing files are left unchanged unless --force is given.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Options:")
	fmt.Fprintln(w, "  --db <driver>   sqlite (default) | postgres | pgvector | mysql.")
	fmt.Fprintln(w, "                  sqlite adds no DB service (uses a named volume).")
	fmt.Fprintln(w, "  --port <port>   Port wired into the image and compose. Default 8080.")
	fmt.Fprintln(w, "  --out <path>    Binary path the Dockerfile copies. Default build/app.")
	fmt.Fprintln(w, "  --force         Overwrite existing Dockerfile / compose.yaml.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Also available as `gebweb build --docker [...]`, which builds the")
	fmt.Fprintln(w, "binary first and then generates the files.")
}
